OENIK_PROG3_2020_2_AL9DVX/SailDoc.Web/Models/Boat.cs
namespace SailDoc.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// Boat Form model and MVC ViewModel.
    /// </summary>
    public class Boat
    {
        /// <summary>
        /// Boat unique id.
        /// </summary>
        public int HajoId { get; set; }

        /// <summary>
        /// Boat registration number.
        /// </summary>
        [Display(Name = "Registration Number")]
        [Required]
        [StringLength(10, MinimumLength = 5)]
        public string Lajstromszam { get; set; }

        /// <summary>
        /// Boat name.
        /// </summary>
        [Display(Name = "Name")]
        [Required]
        [StringLength(100, MinimumLength = 2)]
        public string Nev { get; set; }
    }
}

OENIK_PROG3_2020_2_AL9DVX/SailDoc.Web/Models/BoatListViewModel.cs
namespace SailDoc.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// Display Boat list.
    /// </summary>
    public class BoatListViewModel
    {
        /// <summary>
        /// Boat list.
        /// </summary>
        public List<Boat> Boats { get; set; }

        /// <summary>
        /// Represent willing to edit boat.
        /// </summary>
        public Boat Boat { get; set; }
    }
}

OENIK_PROG3_2020_2_AL9DVX/SailDoc.Web/Controllers/BoatController.cs
namespace SailDoc.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using SailDoc.Data.Models;
    using SailDoc.Logic.Interfaces;
    using SailDoc.Web.Models;

    /// <summary>
    /// Boats controller.
    /// </summary>
    public class BoatController : Controller
    {
        private IBoatLogic boatLogic;
        private IMapper mapper;
        private BoatListViewModel listViewModel;

        /// <summary>
        /// Initializes a new instance of the <see cref="BoatController"/> class.
        /// </summary>
        /// <param name="boatLogic">boat handler instance.</param>
        /// <param name="mapper">mapper instance.</param>
        public BoatController(IBoatLogic boatLogic, IMapper mapper)
        {
            this.boatLogic = boatLogic;
            this.mapper = mapper;

            this.listViewModel = new BoatListViewModel();
            this.listViewModel.Boat = new Models.Boat();

            var boats = this.boatLogic.GettAllBoat();
            this.listViewModel.Boats = this.mapper.Map<IList<Data.Models.Hajo>, List<Web.Models.Boat>>(boats);
        }

        /// <summary>
        /// Land page for boats.
        /// </summary>
        /// <returns>View.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("BoatIndex", this.listViewModel);
        }

        /// <summary>
        /// Get boat details.
        /// </summary>
        /// <param name="id">Boat id.</param>
        /// <returns>View instance.</returns>
        public IActionResult Details(int id)
        {
            return this.View("BoatDetails", this.GetBoat(id));
        }

        /// <summary>
        /// Remove boat.
        /// </summary>
        /// <param name="id">Boat id.</param>
        /// <returns>Message.</returns>
        public IActionResult Remove(int id)
        {
            this.TempData["editResult"] = "Delete successed.";

            this.boatLogic.DeleteBoat(this.boatLogic.GetHajo(id));
            if (this.listViewModel.Boats.Find(b => b.HajoId == id) == null)
            {
                this.TempData["editResult"] = "Delete successed.";
            }

            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// Edit boat.
        /// </summary>
        /// <param name="id">Boat id.</param>
        /// <returns>Edited boat.</returns>
        public IActionResult Edit(int id)
        {
            this.ViewData["editAction"] = "Edit";
            this.listViewModel.Boat = this.GetBoat(id);
            return this.View("BoatIndex", this.listViewModel);
        }

        /// <summary>
        /// Edit or update boat.
        /// </summary>
        /// <param name="boat">Boat instance.</param>
        /// <param name="editAction">Action type.</param>
        /// <returns>Redirect to Index.</returns>
        [HttpPost]
        public IActionResult Edit(Web.Models.Boat boat, string editAction)
        {
            if (this.ModelState.IsValid && boat != null)
            {
                this.TempData["editResult"] = "Insert successed.";
                if (editAction == "AddNew")
                {
                    var tmpB = this.mapper.Map<Web.Models.Boat, Data.Models.Hajo>(boat);
                    this.boatLogic.InsertBoat(tmpB);
                }
                else
                {
                    var boat1 = this.boatLogic.GetHajo(boat.HajoId) ?? new Hajo();
                    boat1.Nev = boat.Nev;
                    boat1.Lajstromszam = boat.Lajstromszam;
                    if (this.boatLogic.UpdateBoat(boat1) == null)
                    {
                        this.TempData["editResult"] = "Update failed.";
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.listViewModel.Boat = boat;
                return this.View("BoatIndex", this.listViewModel);
            }
        }

        private Models.Boat GetBoat(int id)
        {
            Data.Models.Hajo boat = this.boatLogic.GetHajo(id);
            return this.mapper.Map<Data.Models.Hajo, Models.Boat>(boat);
        }
    }
}

OENIK_PROG3_2020_2_AL9DVX/SailDoc.Web/Views/Boat/BoatDetails.cshtml
@model SailDoc.Web.Models.Boat

@{
    ViewData["Title"] = $"Boat Details";
}

<h2>@Html.DisplayFor(m => m.Nev)</h2>

<table border="1">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(m => m.Nev)</th>
            <th>@Html.DisplayNameFor(m => m.Lajstromszam)</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Html.DisplayFor(m => m.Nev)</td>
            <td>@Html.DisplayFor(m => m.Lajstromszam)</td>
        </tr>
    </tbody>
</table>

@Html.ActionLink("Back", "Index")

OENIK_PROG3_2020_2_AL9DVX/SailDoc.Web/Views/Boat/BoatEdit.cshtml
@model SailDoc.Web.Models.Boat

<div>
    <h2>Boat Edit</h2>            

    @using (Html.BeginForm("Edit", "Boat"))
    {
        @Html.ValidationSummary()

        @Html.AntiForgeryToken()

        @Html.HiddenFor(m => m.HajoId)

        @Html.Hidden("editAction", ViewData["editAction"].ToString())

        <div class="edit-label">@Html.LabelFor(m => m.Nev)</div>
        <div class="edit-label">@Html.EditorFor(m => m.Nev)</div>

        <div class="edit-label">@Html.LabelFor(m => m.Lajstromszam)</div>
        <div class="edit-label">@Html.EditorFor(m => m.Lajstromszam)</div>

        <input type="submit" value="Save" />
    }
</div>

OENIK_PROG3_2020_2_AL9DVX/SailDoc.Web/Views/Boat/BoatIndex.cshtml
@model SailDoc.Web.Models.BoatListViewModel

@{
    ViewData["Title"] = "BoatIndex";
}


<p style="color: red">@TempData["editResult"]</p>

@await Html.PartialAsync("BoatEdit", Model.Boat)

@await Html.PartialAsync("BoatList", Model.Boats)

OENIK_PROG3_2020_2_AL9DVX/SailDoc.Web/Views/Boat/BoatList.cshtml
@model IEnumerable<SailDoc.Web.Models.Boat>


<div>
    <h2>Boats</h2>

    @if (Model.Count() == 0)
    {
        <p>There is no boat in the database.</p>
    }
    else
    {
        <table>
            <tr>
                <th>@Html.DisplayNameFor(b => b.First().Nev)</th>
                <th>@Html.DisplayNameFor(b => b.First().Lajstromszam)</th>
                <th>Details</th>
                <th>Edit</th>
                <th>Remove</th>
            </tr>
            @foreach (var boat in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(b => boat.Nev)</td>
                    <td>@Html.DisplayFor(b => boat.Lajstromszam)</td>
                    <td>@Html.ActionLink("[SHOW]", "Details", new { id = boat.HajoId })</td>
                    <td>@Html.ActionLink("[EDIT]", "Edit", new { id = boat.HajoId })</td>
                    <td>@Html.ActionLink("[DEL]", "Remove", new { id = boat.HajoId })</td>
                </tr>
            }
        </table>
    }

</div>